### ISSUE TITLE
Siilihai always fails to download parser

### ISSUE THREAD

**Issue by Drakedude** [vranki/siilihai-client#2]
I'm trying to open a premade parser as a base for my own, but any i click on give me the "failed to download parser" response.

**Comment by vranki** [comment]
Sounds like a bug. Which parser (or any)?

**Comment by Drakedude** [comment]
any

**Comment by vranki** [comment]
Yep, for some reason most parsers can't be downloaded. But i found some that can be. I'm investigating this, thanks for report.

**Comment by vranki** [comment]
Bug found and fixed in git. Parser maker displayed all forums instead of parser forums when opening a parser. This will be fixed in next release. Before that you can check http://siilihai.com/forumlist.html to see which are parsed (not TapaTalk) and download those in PM.

Thanks again for reporting.
